"""add_image_paths

Revision ID: 1e3331800f6a
Revises: 93935c5c94e3
Create Date: 2026-02-25 19:13:59.326062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3331800f6a'
down_revision: Union[str, Sequence[str], None] = '93935c5c94e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_jobs', sa.Column('image_paths', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'image_paths')
    # ### end Alembic commands ###
