"""add image_status column

Revision ID: 386ae8b7ee2d
Revises: 1e3331800f6a
Create Date: 2026-02-25 23:29:52.840960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386ae8b7ee2d'
down_revision: Union[str, Sequence[str], None] = '1e3331800f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_jobs', sa.Column('image_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'image_status')
    # ### end Alembic commands ###
