"""add_audio_path

Revision ID: 93935c5c94e3
Revises: fc56c81a99e9
Create Date: 2026-02-25 16:50:26.377133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93935c5c94e3'
down_revision: Union[str, Sequence[str], None] = 'fc56c81a99e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_jobs', sa.Column('audio_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_jobs', 'audio_path')
    # ### end Alembic commands ###
